import Head from 'next/head'
import Header from '../pages/header'


export default function Home() {
  return (
    <div className="bg-background w-[1350px] h-[900px]  mobile:bg-backgroundTablet md:bg-backgroundTablet md:h-[1024px] md:bg-no-repeat relative  mobile:w-[375px] mobile:h-[667px]  ">
      <Head> 
        <title>Planet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      <div className="">

      <Header />      

      <main className="text-white h-96 flex justify-around">
        <section className="w-[450px] h-[382px] absolute left-[165px]  top-[387px] 
        md:w-[450px] md:h-[334px] md:top-[202px] md:left-[159px] md:absolute
        mobile:absolute mobile:w-[327px] mobile:h-[276px]  mobile:left-[24px] mobile:top-[112px]   ">
          <p className="text-3xl font-body2 leading-8 tracking-wider  
          md:h-[24px] md:left-[90px] md:text-[20px] md:leading-[24px] md:tracking-[3.38px] md:font-body2  md:text-center
          mobile:w-[227px] mobile:h-[19px] mobile:left-[16.82%] mobile:right-[16.82%] mobile:top-[calc(50%-19px/2-128.5px)] mobile:text-base mobile:leading-[19px] mobile:text-center mobile:tracking-[2.7px] mobile:font-[#D0D6F9]
          ">SO, YOU WANT TO TRAVEL TO <span className="block font-body text-9xl mb-8 mt-8 
          md:w-[445px] md:h-[150px] md:top-[48px] md:text-[150px] md:leading-[150px]
          mobile:absolute  mobile:w-[327px] mobile:h-[100px] mobile:left-[0%] mobile:right-[0%] mobile:top-[calc(50%-100px/2-53px)] mobile:text-[80px] mobile:leading-[100px] mobile:text-center mobile:font-[#FFFFFF]
         "> SPACE </span> </p>
          <p className="text-lg leading-8 font-normal font-body1 h-32  w-96
          md:w-[444px] md:h-[112px] md:left-[3px] md:top-[222px] md:absolute md:font-body1 md:text-base md:leading-[28px] md:text-center
          mobile:w-[327px]  mobile:absolute mobile:h-[125px] mobile:right-[0%] mobile:left-[0%] mobile:top-[calc(50%-125px/2+75.5px)] mobile:text-[15px] mobile:leading-[25px] mobile:text-center mobile:font-[#D0D6F9]
          ">Let's face it: if you want to go to space,you might as well
            genuinely go to outer space and not hover kind of on the  edge of it.
            Well sit back, and relax because we'll give you a truly out of this world
            experience.
          </p>
        </section>
        <section className=" bg-white w-[274px]  h-[274px] mt-24 rounded-full absolute left-[1001px]  top-[495px]
          md:w-[242px] md:h-[242px] md:top-[650px] md:left-[263px] md:absolute
          mobile:absolute mobile:w-[150px] mobile:h-[150px] mobile:left-[113px] mobile:top-[400px] 
        ">
        
          <h3 className="text-black text-3xl absolute top-28 left-16 font-body font-normal tracking-widest 
          md:w-[148px] md:h-[37px] md:top-[103px] md:left-[46px] md:text-[32px] md:leading-[36.67px] md:tracking-[2px]
          mobile:w-[93px] mobile:h-[23px] mobile:left-[19.67%] mobile:right-[18.33%] mobile:top-[calc(50%-23px/2+4.5px)] mobile:text-[20px] mobile:leading-[23px] mobile:text-center mobile:tracking-[1.25px] mobile:font-[#0B0D17]
          ">EXPLORE</h3>
          

        </section>
        </main>

      </div>
    </div> 
  )
}
