import Head from 'next/head'
import Header from '../pages/header'


export default function Home() {
  return (
    <div className=" w-full bg-[url('/background-home-mobile.jpg')] bg-no-repeat bg-cover box-border relative  text-white min-h-screen
    md:bg-[url('/background-home-tablet.jpg')] 
    lg:bg-[url('/background-home-desktop.jpg')]
    ">
      <Head> 
        <title>Planet</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>
      <div className="">

      <Header />      

      <main className="flex flex-col justify-evenly items-center h-screen  mt-12 
         lg:w-full lg:mt-0 lg:flex-row  
      ">
        <section className="h-[17.25rem] w-full 
        md:w-[28.125rem]  md:h-[20.875rem]
         lg:ml-[10.3125rem]
        ">
          <p className="font-normal text-base leading-5 tracking-wide font-[BarlowCondensed] text-center text-[#D0D6F9]
          md:text-xl md:leading-6 md:tracking-[3.375px] lg:text-3xl lg:leading-9 lg:tracking-[4.725px]
          ">SO, YOU WANT TO TRAVEL TO <span className="  mx-auto  w-[20.4375rem] h-[6.25rem]  block font-[Bellefair] font-normal text-[5rem] leading-[6.25rem] text-center text-[#FFFFFF]
         md:text-[9.375rem] md:leading-[9.375rem] md:mx-0 md:mt-4 lg:leading-[10.75rem] 
         "> SPACE </span> </p>
          <p className=" mx-auto w-[20.4375rem] h-[7.8125rem]   font-normal text-[15px] text-center font-[Barlow] leading-6 text-[#D0D6F9] px-4
          md:text-base md:leading-7 md:w-[27.75rem] md:mt-12 lg:leading-8 lg:text-xl
          ">Let's face it: if you want to go to space,you might as well
            genuinely go to outer space and not hover kind of on the  edge of it.
            Well sit back, and relax because we'll give you a truly out of this world
            experience.
          </p>
        </section>
        <section className=" rounded-full h-[9.375rem] w-[9.375rem] bg-white mx-auto box-border relative mt-6
        md:w-[15.125rem] md:h-[15.125rem] md:mt-0
        lg:w-[17.125rem] lg:h-[17.125rem] lg:mr-[10.3125rem]
        
        ">
        
          <h3 className="font-[Bellefair] text-xl leading-6 tracking-[1.25px] text-[#0B0D17] text-center pt-16
          md:text-[2rem] md:leading-9 md:tracking-[2px] md:text-center md:pt-24 lg:pt-28
          ">EXPLORE</h3>
          

        </section>
        </main>

      </div>
    </div> 
  )
}
